fixes setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,19 +1,9 @@
 #!/bin/bash
 
-__symlink_homefiles() {
-  local dotfiles do_symlink do_force
-  dotfiles="$(ls -a ./bootstrap/home | grep -E '\.[a-z]+')"
+HOME_FILES="$(ls -a "$HOME/dotfiles/home" | grep -E '\.[a-z]+')"
 
-  if [[ "$1" != "-f" ]]; then
-    printf "%s" "Would you like to symlink the following files to $HOME?\n$dotfiles\n[y/N] \c"
-    read -r do_symlink
-
-    if [[ "$do_symlink" != "y" ]]; then
-      exit 0
-    fi
-  fi
-
-  for file in $dotfiles
+symlink_homefiles() {
+  for file in $HOME_FILES
   do
     if [[ "$file" == "." ]] || [[ "$file" == ".." ]]; then
       continue
@@ -29,20 +19,88 @@ __symlink_homefiles() {
   done
 }
 
+install_oh_my_zsh() {
+  if ! sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"; then
+    echo 'Oh My ZSH install failed. Aborting.'
+    exit 1
+  fi
+}
+
+install_zsh_autosuggestions() {
+  if ! git clone https://github.com/zsh-users/zsh-autosuggestions "$HOME/.zsh/zsh-autosuggestions"; then
+    echo 'Git clone failed. Aborting.'
+    exit 1
+  fi
+}
+
+if [ ! -d "$HOME/.oh-my-zsh" ]; then
+  if [ -n "$SPIN" ]; then
+    echo '1/5. Installing Oh My ZSH'
+    install_oh_my_zsh
+  else
+    printf "%s" "1/5. Install Oh My ZSH? [y/N] "
+    read -r do_install_oh_my_zsh
+
+    if [[ "$do_install_oh_my_zsh" == 'y' ]]; then
+      install_oh_my_zsh
+    fi
+  fi
+else
+  echo '1/5. Installing Oh My ZSH. (already installed)'
+fi
+
 if [ -n "$SPIN" ]; then
-  echo 'initializing kvendrik/dotfiles'
+  echo '2/5. Symlinking the custom Oh My ZSH theme'
+  ln -sf "$HOME/dotfiles/zsh_themes/robbyrussell_with_host.zsh-theme" "$HOME/.oh-my-zsh/custom/themes/robbyrussell_with_host.zsh-theme"
+else
+  printf "%s" "2/5. Would you like to symlink the custom Oh My ZSH theme? [y/N] "
+  read -r custom_zsh_theme_install
 
-  __symlink_homefiles -f
+  if [[ "$custom_zsh_theme_install" == 'y' ]]; then
+    ln -sf "$HOME/dotfiles/zsh_themes/robbyrussell_with_host.zsh-theme" "$HOME/.oh-my-zsh/custom/themes/robbyrussell_with_host.zsh-theme"
+  fi
+fi
 
-  export GITHUB_USERNAME='kvendrik'
-  export REPOSITORIES_DIRECTORY='/src/github.com/shopify'
+if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
+  if [ -n "$SPIN" ]; then
+    echo '3/5. Installing ZSH Autosuggestions'
+    install_zsh_autosuggestions
+  else
+    printf '%s' '3/5. Install ZSH Autosuggestions? [y/N] '
+    read -r do_install_zsh_autosuggestions
 
-  # shellcheck disable=SC1091
-  source "$HOME/dotfiles/index"
+    if [[ "$do_install_zsh_autosuggestions" == 'y' ]]; then
+      install_zsh_autosuggestions
+    fi
+  fi
+else
+  echo '3/5. Installing ZSH Autosuggestions. (already installed)'
+fi
+
+if [ -n "$SPIN" ]; then
+  echo '4/5. Symlinking home files'
+  symlink_homefiles -f
+else
+  printf "%s\n%s\n%s" "4/5. Would you like to symlink the following files to $HOME?" "$HOME_FILES" "[y/N] "
+  read -r do_symlink
+
+  if [[ "$do_symlink" == "y" ]]; then
+    symlink_homefiles
+  fi
+fi
+
+if [ -n "$SPIN" ]; then
+  echo "5/5. Adding Spin configuration to $HOME/.rc-config"
+  echo """
+export GITHUB_USERNAME='kvendrik'
+export REPOSITORIES_DIRECTORY='/src/github.com/shopify'
+  """ > "$HOME/.rc-config"
 
   exit 0
 fi
 
-__symlink_homefiles
+echo "5/5. Manually import the Terminal theme found in $HOME/dotfiles/CustomBasic.terminal into your Terminal preferences"
+printf '%s' 'Done? [y/n] '
+read -r done_manually_importing_theme
 
-echo "Done. Check out the README.md for further instructions."
+printf '\n%s' "[✓] Done. Check out the README.md for further instructions."
