fixes setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -6,6 +6,7 @@ if [ ! -d "$HOME/dotfiles/home" ]; then
 fi
 
 HOME_FILES="$(ls -a "$HOME/dotfiles/home" | grep -E '\.[a-z]+')"
+SETUP_STEPS='9'
 
 symlink_homefiles() {
   for file in $HOME_FILES
@@ -48,10 +49,10 @@ at any point you can run it again to continue where you left off.
 
 if [ ! -d "$HOME/.oh-my-zsh" ]; then
   if [ -n "$SPIN" ]; then
-    echo '1/7. Installing Oh My ZSH'
+    echo "1/$SETUP_STEPS. Installing Oh My ZSH"
     install_oh_my_zsh
   else
-    printf "%s" "1/7. Install Oh My ZSH? [y/N] "
+    printf "%s" "1/$SETUP_STEPS. Install Oh My ZSH? [y/N] "
     read -r do_install_oh_my_zsh
 
     if [[ "$do_install_oh_my_zsh" == 'y' ]]; then
@@ -59,15 +60,15 @@ if [ ! -d "$HOME/.oh-my-zsh" ]; then
     fi
   fi
 else
-  echo '1/7. Installing Oh My ZSH. (already installed)'
+  echo "1/$SETUP_STEPS. Installing Oh My ZSH. (already installed)"
 fi
 
 if [ -n "$SPIN" ]; then
-  echo '2/7. Symlinking the custom Oh My ZSH theme'
+  echo "2/$SETUP_STEPS. Symlinking the custom Oh My ZSH theme"
   echo "    symlinking $HOME/dotfiles/zsh-themes/robbyrussell_with_host.zsh-theme to $HOME/.oh-my-zsh/custom/themes/robbyrussell_with_host.zsh-theme"
   ln -sf "$HOME/dotfiles/zsh-themes/robbyrussell_with_host.zsh-theme" "$HOME/.oh-my-zsh/custom/themes/robbyrussell_with_host.zsh-theme"
 else
-  printf "%s" "2/7. Would you like to symlink the custom Oh My ZSH theme? [y/N] "
+  printf "%s" "2/$SETUP_STEPS. Would you like to symlink the custom Oh My ZSH theme? [y/N] "
   read -r custom_zsh_theme_install
 
   if [[ "$custom_zsh_theme_install" == 'y' ]]; then
@@ -78,10 +79,10 @@ fi
 
 if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
   if [ -n "$SPIN" ]; then
-    echo '3/7. Installing ZSH Autosuggestions'
+    echo "3/$SETUP_STEPS. Installing ZSH Autosuggestions"
     install_zsh_autosuggestions
   else
-    printf '%s' '3/7. Install ZSH Autosuggestions? [y/N] '
+    printf '%s' "3/$SETUP_STEPS. Install ZSH Autosuggestions? [y/N] "
     read -r do_install_zsh_autosuggestions
 
     if [[ "$do_install_zsh_autosuggestions" == 'y' ]]; then
@@ -89,14 +90,14 @@ if [ ! -d "$HOME/.zsh/zsh-autosuggestions" ]; then
     fi
   fi
 else
-  echo '3/7. Installing ZSH Autosuggestions. (already installed)'
+  echo "3/$SETUP_STEPS. Installing ZSH Autosuggestions. (already installed)"
 fi
 
 if [ -n "$SPIN" ]; then
-  echo '4/7. Symlinking home files'
+  echo "4/$SETUP_STEPS. Symlinking home files"
   symlink_homefiles -f
 else
-  printf "%s\n%s\n%s" "4/7. Would you like to symlink the following files to $HOME?" "$HOME_FILES" "[y/N] "
+  printf "%s\n%s\n%s" "4/$SETUP_STEPS. Would you like to symlink the following files to $HOME?" "$HOME_FILES" "[y/N] "
   read -r do_symlink
 
   if [[ "$do_symlink" == "y" ]]; then
@@ -105,7 +106,7 @@ else
 fi
 
 if [ -n "$SPIN" ]; then
-  echo "5/7. Adding Spin configuration to $HOME/.rc-config and $HOME/.rc-extra"
+  echo "5/$SETUP_STEPS. Adding Spin configuration to $HOME/.rc-config and $HOME/.rc-extra"
 
   echo """
 export GITHUB_USERNAME='kvendrik'
@@ -116,38 +117,57 @@ export REPOSITORIES_DIRECTORY='/src/github.com/shopify'
 eval \`dircolors ~/.dircolors\`
   """ > "$HOME/.rc-extra"
 else
-  printf '%s' "5/7. Manually import the Terminal theme found in $HOME/dotfiles/CustomBasic.terminal into your Terminal preferences. Done? [y/n] "
+  printf '%s' "5/$SETUP_STEPS. Manually import the Terminal theme found in $HOME/dotfiles/CustomBasic.terminal into your Terminal preferences. Done? [y/n] "
   read -r done_manually_importing_theme
 fi
 
-do_install_homebrew_deps="y"
+homebrew_installed='y'
 
 if [ ! -x "$(command -v brew)" ]; then
   if [ -n "$SPIN" ]; then
-    echo '6/7. Installing Homebrew'
+    echo "6/$SETUP_STEPS. Installing Homebrew"
     install_homebrew
   else
-    printf '%s' '6/7. Install Homebrew and Homebrew dependencies? [y/N] '
+    printf '%s' "6/$SETUP_STEPS. Install Homebrew? [y/N] "
     read -r do_install_homebrew
     if [[ "$do_install_homebrew" == 'y' ]]; then
       install_homebrew
     else
-      do_install_homebrew_deps="n"
+      homebrew_installed='n'
     fi
   fi
 else
-  echo '6/7. Installing Homebrew. (already installed)'
+  echo "6/$SETUP_STEPS. Installing Homebrew. (already installed)"
+fi
+
+if [[ "$homebrew_installed" == 'n' ]]; then
+  echo "7/$SETUP_STEPS. Install missing Homebrew dependencies. (skipped)"
+  do_install_homebrew_deps='n'
+else
+  printf '%s' "7/$SETUP_STEPS. Install missing Homebrew dependencies? [y/N] "
+  read -r do_install_homebrew_deps
 fi
 
 if [ ! -x "$(command -v fzf)" ]; then
   if [[ "$do_install_homebrew_deps" == 'y' ]]; then
-    echo '7/7. Installing fzf'
+    echo "8/$SETUP_STEPS. Installing fzf"
     brew install fzf
   else
-    echo '7/7. Installing fzf. (skipping)'
+    echo "8/$SETUP_STEPS. Installing fzf. (skipping)"
   fi
 else
-  echo '7/7. Installing fzf. (already installed)'
+  echo "8/$SETUP_STEPS. Installing fzf. (already installed)"
+fi
+
+if ! git squash -h &> /dev/null; then
+  if [[ "$do_install_homebrew_deps" == 'y' ]]; then
+    echo "9/$SETUP_STEPS. Installing kvendrik/git-squash"
+    brew install kvendrik/osx/git-squash
+  else
+    echo "9/$SETUP_STEPS. Installing kvendrik/git-squash. (skipping)"
+  fi
+else
+  echo "9/$SETUP_STEPS. Installing kvendrik/git-squash. (already installed)"
 fi
 
 printf '\n%s' "[✓] Done. Check out the README.md for further instructions."
