Adds script to ensure repo backups

diff --git a/scripts/ensure-repos-backed-up b/scripts/ensure-repos-backed-up
--- a/scripts/ensure-repos-backed-up
+++ b/scripts/ensure-repos-backed-up
@@ -12,37 +12,45 @@ error_found=0
 for folder_name in `ls $repos_path`; do
   folder_path="$repos_path/$folder_name"
 
-  cd $folder_path
-  echo -n "Checking $folder_path..."
+  if [ ! -d "$folder_path" ]; then
+    continue
+  fi
 
-  if ! git rev-parse --is-inside-work-tree; then
-    echo "is not a Git repository."
+  echo "Checking $folder_name"
+  cd $folder_path
+
+  if ! git rev-parse --is-inside-work-tree &> /dev/null; then
+    echo "$folder_path: is not a Git repository."
     error_found=1
     continue
   fi
 
   if [ -n "$(git status -s)" ]; then
-    echo "could not check because of uncommited changes."
+    echo "$folder_path: could not check because of uncommited changes."
     error_found=1
     continue
   fi
 
   if [[ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]]; then
-    echo "could not check because project is not on master branch."
+    echo "$folder_path: could not check because project is not on master branch."
     error_found=1
     continue
   fi
 
   if [[ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]]; then
-    echo "could not check because project is not on master branch."
+    echo "$folder_path: could not check because project is not on master branch."
     error_found=1
     continue
   fi
 
-  git remote update
+  if ! git remote update &> /dev/null; then
+    echo "$folder_path: error while fetching remote."
+    error_found=1
+    continue
+  fi
 
-  if [ -n "$(git log HEAD..origin/master --oneline)" ]; then
-    echo "is out of date."
+  if [ -n "$(git log origin/master..HEAD --oneline)" ]; then
+    echo "$folder_path: local copy is ahead of remote."
     error_found=1
     continue
   fi
